name: build-windows

on: [ push, pull_request ]

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows MSVC Debug",
            artifact: "windows-msvc-debug.zip",
            cc: "cl",
            cxx: "cl",
            cmake_build_options: "--config Debug",
            cmake_configure_options: '-G "Visual Studio 16 2019" -A x64',
            build_type: "Debug"
          }
          - {
            name: "Windows MSVC Release",
            artifact: "windows-msvc-release.zip",
            cc: "cl",
            cxx: "cl",
            cmake_build_options: "--config Release",
            cmake_configure_options: '-G "Visual Studio 16 2019" -A x64',
            build_type: "Release"
          }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Building & Installing LLVM
        run: |
          git clone https://github.com/llvm/llvm-project/ --branch llvmorg-13.0.0 --single-branch --depth=1
          cd llvm-project
          cmake -S llvm -B build -D CMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -D CMAKE_CXX_FLAGS="/MP" -D LLVM_PARALLEL_LINK_JOBS=1 -D LLVM_ENABLE_PROJECTS="llvm;lld" -D LLVM_TARGETS_TO_BUILD="X86" -T host=x64 ${{ matrix.config.cmake_configure_options }}
          cmake --build build --target install ${{ matrix.config.cmake_build_options }}

      - name: Configure CMake
        run: |
          set CC=${{ matrix.config.cc }}
          set CXX=${{ matrix.config.cxx }}

          cmake . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} ${{ matrix.config.cmake_configure_options }}

      - name: Build
        run: |
          cmake --build build ${{ matrix.config.cmake_build_options }}

      - name: Prepare upload
        run: |
          7z a -tzip ${{ matrix.config.artifact }} build/*

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          path: ${{ matrix.config.artifact }}
          name: ${{ matrix.config.artifact }}
